title: Subhajit Paul
author: Subhajit Paul
subtitle: Exploring the Intersection of Formal Verification and Generative AI

url: "https://subhajit-paul.github.io"
baseurl: "/"

footer_only_homepage: true
footer_url: "https://github.com/Subhajit-Paul"
footer_text: "Research at ISI Kolkata | Formal Verification & AI"

profile-picture: assets/profile.png
favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css
    
include:
  - setup.sh

navbar:
 - name: "About"
   link: "about"
 - name: "Research"
   link: "publications"
 - name: "Download CV"
   link: "cv"
 - name: "Portfolio"
   absolute-link: "https://subhajit-paul.vercel.app/about"
